language: node_js
node_js:
- '20'
sudo: required
addons:
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
- npm install -g typescript jest && tsc -v
install:
- npm install
script:
- npm run test
- npm run build