version: '3.9'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules

services:
  time2blocks-dev:
    image: time2blocks-dev
    container_name: time2blocks-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /time2blocks
    volumes:
      - ..:/time2blocks:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules_vol:/time2blocks/node_modules
    tty: true
