services:
  time2blocks-dev:
    image: time2blocks-dev
    container_name: time2blocks-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /time2blocks
    volumes:
      - ..:/time2blocks:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
